title: Coding with Karan
author: Karan Dhillon
email: me@codingwithkaran.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a Mobile Engineer who works for a Toronto based company called Homestars, Inc.
  I love working on android applications where I incorporate clean architecture along with 
  SOLID principles all enforced by a Test Driven Development (TDD) approach.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codingwithkaran.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: karandhillon95
github_username:  karandhillon
include: ['_pages']

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
